subscriber_1  | /subscribers.go:95:2: undefined: runtime
subscriber_1  | /subscribers.go:105:22: undefined: nats.DisconnectErrHandler                
                        

version: '3'
services:
    server:
        image: nats
        container_name: natsio-server_1
        expose:
        - "4222"
        ports:
        - "8222:8222"
        hostname: nats-server
    publisher:
        build: ./pubs
        ports:
            - "8080:8080"
        environment:
            - "NATS_URI=nats://nats:4222"
        depends_on:
            - server
    subscriber:
        build: ./subs
        restart: on-failure
        environment:
            - "NATS_URI=nats://nats:4222"   
        ports:
            - "8181:8181"                 
        depends_on:
            - server