networks:
  GooglePubSub:
    name: GooglePubSub
    driver: bridge

services:
  publisher:
    build:
      context: ./server
    image: publisher
    ports:
      - "80:8080"
    networks:
      - GooglePubSub
  subscriber:
    build:
      context: ./client
    image: "subscriber"
    networks:
      - GooglePubSub