version: '3.9'

networks:
  GooglePubSub:
    name: GooglePubSub
    driver: bridge

services:
  publisher:
    build:
      context: ./server
    image: s1_publisher
    ports:
      - "80:8080"
    networks:
      - GooglePubSub
  subscriber:
    build:
      context: ./client
    image: "s2_subscriber"
    networks:
      - GooglePubSub